# Generated by Django 6.0.3 on 2026-03-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='categroy',
            new_name='category',
        ),
    ]
