# Generated by Django 6.0.3 on 2026-04-16 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章正文')),
                ('category', models.CharField(default='日常', max_length=200, verbose_name='文章分类')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('views', models.IntegerField(default=0, verbose_name='阅读量')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='文章摘要')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
