# Generated by Django 6.0.3 on 2026-03-21 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资料分类',
                'verbose_name_plural': '资料分类',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资料标题')),
                ('file', models.FileField(upload_to='materials/', verbose_name='资料文件')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('categroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '复习资料',
                'verbose_name_plural': '复习资料',
            },
        ),
    ]
